# Generated by Django 2.1.5 on 2021-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
